spring:
  datasource:
    url: jdbc:postgresql://prod-db-server:5432/user_db_stage
    username: postgres
    password: password_prod
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: prod
    placeholders:
      schema: prod
mybatis:
  mapper-locations: classpath:mapper/*.xml

