spring:
  datasource:
    url: jdbc:postgresql://154.23.243.155:5432/postgres
    username: gitea_Gk2NEP
    password: gitea_7Em7JB
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: stage
    placeholders:
      schema: stage
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8082